# Generated by Django 4.2.10 on 2024-02-18 14:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="city name")),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                ("address", models.CharField(max_length=150, verbose_name="address")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+799999999'. 10 digits allowed.",
                                regex="^\\+?7?\\d{10}$",
                            )
                        ],
                        verbose_name="phone",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city",
                        to="catalog.city",
                        verbose_name="city name",
                    ),
                ),
            ],
            options={
                "verbose_name": "hotel",
                "verbose_name_plural": "hotels",
            },
        ),
    ]
